name: ebame7-aDNA-tutorial
channels:
  - conda-forge
  - bioconda
  - defaults
  - genomewalker
dependencies:
  - python=3.9
  - bowtie2
  - seqkit
  - samtools>=1.14
  - picard
  - bedtools
  - mapdamage2
  - htslib
  - csvtk
  - htslib
  - cxx-compiler
  - gsl
  - eigen
  - pip
  - pip:
      - bam-filter>=1.0.13
      - dmg-reads>=1.0.0
      - attrs
      - metaDMG[all]>=0.36.0
      - tabview
      - logger_tt
